USE master;
GO

-- create the sales database
CREATE DATABASE SALES_DB;
GO

-- drop the sales database
IF DB_ID('SALES_DB') IS NOT NULL
BEGIN
	ALTER DATABASE SALES_DB
	SET SINGLE_USER -- or RESTRICTED_USER
	WITH ROLLBACK IMMEDIATE;

	DROP DATABASE SALES_DB;
END;
GO

-- recreate the sales database securely by dropping active connections
IF DB_ID('SALES_DB') IS NOT NULL
BEGIN
	ALTER DATABASE SALES_DB
	SET SINGLE_USER -- or RESTRICTED_USER
	WITH ROLLBACK IMMEDIATE;

	DROP DATABASE SALES_DB;
END;
GO

CREATE DATABASE SALES_DB;
GO
